OpenXiangShan/Utility

src/main/scala/utility/ChiselDB.scala
src/main/scala/utility/Constantin.scala

1. Constantin: When FPAG is enabled, constantin switches from file read to initialization parameter.
2. ChiselDB: add envInFPGA member variables for later use

Tool: cancel DIP-C write when in FPGA 

---

src/main/scala/utility/RegisterSlice.scala

Register Slice has three types, Mainly used to handle timing problem：
- also called skid buffer
<html>
<body>
<!DOCTYPE html><br class="Apple-interchange-newline">
  | Forward Registered | Backward Registered | Fully Registered
-- | -- | -- | --
Latency | 1 | 0 | 1
io.in.ready | comb with io.out.ready | reg out | reg out
io.out.bits | reg out | comb with io.in.bits | reg out
io.out.valid | reg out | comb with io.in.valid | reg out
</body>
</html>
- Latency means from io.in.fire to io.out.fire

add RegisterSlice.scala

---

src/main/scala/utility/Constantin.scala

`getPreProcessFromStdInCpp` in `src/main/scala/utility/Constantin.scala` is missing a call to `constantinInit();`, resulting in all constants being setting to zero when only a subset of constants is provided through standard input. Fix it.
`src/main/scala/utility/Constantin.scala` 中的 `getPreProcessFromStdInCpp` 漏掉了初始化函数 `constantinInit();`。这使得，开启 `AutoSolving` 选项后（即从标准输入流输入），如果只提供一部分常量时，其他所有常量都会被错误地设为 0。修复了这个问题。

fix: constantin init when load from stdin

---

src/main/scala/utility/Constantin.scala

This should partially resolve https://github.com/OpenXiangShan/XiangShan/issues/2561.
This PR should be squash and merge.

Constantin: avoid assigning DPI-C value to wire directly

---

src/main/scala/utility/SRAMTemplate.scala

Add an option `useBitmask` in SRAMTemplate to support bitmasking.
The underlying mechanism uses UInt(1) in Chisel's SyncReadMem when bitmasking.
This involves a major rewrite of some interface code, so should be **extensively reviewed and discussed**.
This version of the code can pass compilation and run normally after fixing some way mask width problems in the XiangShan master branch.

Support bitmasking in SRAMTemplate

---

src/main/scala/utility/LookupTree.scala
src/main/scala/utility/MIMOQueue.scala

Some deprecated APIs in chisel 3.6.0 have been deleted in chisel 6.0.0-RC2. This PR replaces them.

chore: replace deprecated APIs

---

src/main/scala/utility/ChiselDB.scala

you can close the ChiselDB only using `WITH_CHISELDB=0` in Makefile with no business of `basicDB`.

Fix switch chisel db

---

src/main/scala/utility/Constantin.scala

Constantin reads the NOOP_HOME env dynamically during simulation. This requires the env to be always set during simulation time. However, this requirement seems useless as the user seldom changes the env path.
This commit adds the compile-time NOOP_HOME variable as the fallback option if the env variable is not set during simulation time.

Constantin: use compile-time env if possible

---

src/main/scala/utility/ClockGate.scala

By encapsulating clockgate as a class, you can reduce the number of lines that repeat operations on the interface when invoked

Clock: Encapsulate ClockGate as an object

---

src/main/scala/utility/ParallelMux.scala

According to these profiler results, `ParallelMux` in TLB is causing around 5% verilog generation time.
This PR remove the `cloneType` in `0.U.asTypeOf()`

util: remove cloneType in ParallelMux

---

src/main/scala/utility/ClockGatedReg.scala
src/main/scala/utility/Hold.scala

1. add `GatedValidRegNext` of bool vector, `GatedValidRegNextN`, `GatedRegNext` and `GatedRegNextN`
2. fix DelayNWithValid compile bug due to no use of K and error hardware type of data

clockgate: add more methods and fix original bug

---

src/main/scala/utility/LogUtils.scala
src/main/scala/utility/PerfCounterUtils.scala

Currently, log and perf utilities such as `XSPerfAccumulate` are implemented in many repositories like XiangShan, CoupledL2 and HuanCun. This PR unifies them and put them in Utility repository.

XSLogPerf: transfer XSLogPerf from XiangShan repository

---

src/main/scala/utility/ClockGatedReg.scala

GatedRegEnable: add `enable` parameter base on GatedRegNext
GatedRegEnable.dupRegs and SegmentedAddrNext.dupAddrs: Deal with the clock gate efficiency of [duplicate regs](https://github.com/OpenXiangShan/XiangShan/commit/868d6014398e965774f26b1bf3760f47215dd641) in frontend of XiangShan.

clock gate: add functions for duplicate regs

---

src/main/scala/utility/ChiselDB.scala

Previous version allocates **64bits** in _char* sql_ for every item,
but such item(uint64) is printed using %ld, so it will eventually become a string of at most 20 digits(char[20]),
and that is 20 * sizeof(char) = **160 > 64**, resulting in overflow of _char* sql_
We solve this by printing with %#lx -> 0x123ABC (at most 16 digits),
and we allocate 16 * sizeof(char) = 128bits for every item

ChiselDB: fix char* buffer may overflow

---

src/main/scala/utility/AXI4Utils/AXI4Error.scala

The commit implements an AXI4 device **`AXI4Error`** base on `AXI4SlaveNode` of diplomacy to handle system level illegal address access, so that under simulation environment SoC can handle non-data error and LSU in XiangShan will raise store/load access fault.

AXI4Utils: add AXI4Error to handle system level illegal address access

---

src/main/scala/utility/SubVec.scala

add sub vector method including remainder, which can be used to support multi-port output for queue/buffer.

feat(subvec): add sub vector method including remainder

---

src/main/scala/utility/Sort.scala

This PR support a small combinational sorter that can sort up to 4 data by Ptr in hardware level.
* size = 1, return the origin data
* size = 2, compare and swap
* size = 3, compare logic is as follows. The same color represents a comparison. Black line represents the result without swap and other color line represents the result swapped.
* size = 4, same as above
Reference:
* https://github.com/OpenXiangShan/XiangShan/blob/d4ca2db4b3d45add495358a040aa2b9f26e40370/src/main/scala/xiangshan/mem/prefetch/L1PrefetchComponent.scala#L103
* https://github.com/freechipsproject/chisel-bootcamp/blob/master/2.3_control_flow.ipynb

feat(sort): support hardware sort

---

src/main/scala/utility/BitUtils.scala

Based on the implementation of paper [Cortadella J, Llaberia Griñó J M, 1992](https://upcommons.upc.edu/bitstream/handle/2117/124893/00177318.pdf?sequence=1), it is used to reduce the operation time of `A+B=K`, e.g. load instruction generate the virtual address and query the TLB at the same stage.
- Cortadella J, Llaberia Griñó J M. Evaluation of A+ B= K conditions without carry propagation[J]. IEEE Transactions on Computers, 1992, 41(11): 1484-1488.[Link](https://upcommons.upc.edu/bitstream/handle/2117/124893/00177318.pdf?sequence=1).

feat(BitUtils): add fast adder comparator support

---

src/main/scala/utility/LogUtils.scala

This change add WireInit to LogUtils' apply, converting some subacces data, like vec element with dynamic index, to data can be probed.

fix(LogUtils): support probe subaccess data

---

src/main/scala/utility/Select.scala

* `Select` is a set of object designed to select the element from an input sequence by self-defined function.
- e.g. Select oldest element from `LoadQueueRAW`
```
val oldest = SelectByFn(
ins         = lqViolationSel,
sels        = lqViolationSel.map(_.bits.uop.robIdx),
fn          = (a: RobPtr, b: RobPtr) => isBefore(a, b),  // `fn` return true choose `a`, otherwise choose `b`
moduleName  = Some("LoadQueueRAW rollback select")
)
```

feat(Select): add Select utility

---

src/main/scala/utility/ChiselPerfCCT.scala

pc is unsigned, but sqlite3 only supports signed integer [-2^63, 2^63-1], if real pc > 2^63-1, it will be stored as negative number, (negtive pc = real pc - 2^64), when read a negtive pc, real pc = negtive pc + 2^64.

    fix(perfcct): fix too large pc store/read error. 

---

src/main/scala/utility/sram/SRAMTemplate.scala

Split large SRAM into smaller SRAM blocks. This class draws inspiration from coupledL2-SplittedSRAM.
As the SplittedSRAM class cannot be fully compatible with the parameters of the FoldedSRAMTemplate class, the SplittedSRAMTemplate class is therefore defined.
1. Modifications to coupledL2-SplittedSRAM require introducing additional parameters.
2. Latency parameter incompatibility exists between the two implementations.
3. Optionally remove redundant parameters from FoldedSRAMTemplate and implement useBitmask support in coupledL2-SplittedSRAM.

feat(FoldedSRAMTemplate): add parameters for splitting

---

src/main/scala/utility/sram/SRAMTemplate.scala

When creating the SplittedSRAMTemplate class, flaws in the code related to the split parameters were overlooked. While the incorrect parameters did not affect functional correctness, they impacted SRAM size configuration.

fix(FoldedSRAMTemplate): fix SRAM split parameters not working in FoldedSRAMTemplate

---

src/main/scala/utility/sram/SRAMTemplate.scala

The timing of feeding a stable PC value after BPU reset differs from the reset timing of ren_vec in the SplittedSRAMTemplate. Directly updating ren_vec using the lower bits of the PC may introduce X-state propagation.

fix(FoldSRAMTemplate): modify the assignment logic of ren_vec to avoid X-state issues.

---

src/main/scala/utility/ChiselDB.scala
src/main/scala/utility/ChiselPerfCCT.scala

PerfCCT(performance counter commit trace) is a Instruction-level granularity perfCounter like GEM5
How to use this:
1. Make with "WITH_CHISELDB=1" argument
2. Run with "--dump-db --dump-select-db lifetime", then get the database
3. Instruction lifetime visualize run "python3 scripts/perfcct.py "the-db-file-path" -p 1 -v  | less"
4. Analysis script now is in XS-GEM5 repo, see https://github.com/OpenXiangShan/GEM5/blob/xs-dev/util/ClockAnalysis.py
How it works:
1. Allocate one unique tag "seqNum" like GEM5 for each instruction at fetch stage
2. Passing the "seqNum" in each pipeline
3. Recording perf data through the DPIC interface

feat: add PerfCCT frame, record inst lifetime

---

src/main/scala/utility/package.scala
src/main/scala/utility/sram/SRAMTemplate.scala
src/test/scala/utility/TestSRAMTemplate.scala

Hello, this change set adds a new option to the dual-port SRAM template called conflictBehavior, which determines what happens when there is a read-write conflict (a simultaneous read and write to the same index). This was implemented following the discussion in OpenXiangShan/XiangShan#4242.
Background: The behavior of SRAM macros during a read-write conflict varies. In the best case, the macro just corrupts the read result for the ways that were written. In the worst case, conflicts are a DRC violation and we must ensure they never occur. Either way, additional logic is often needed to handle conflicts, which changes based on the behavior of the macro, and the desired behavior of the interface. Since SRAMs are used many times in different parts of the design, it's best to put this …

Add multiple modes for handling read-write conflicts in dual-port SRAMs

---

src/main/scala/utility/ChiselDB.scala

Chisel currently allows zero width signals / ports and just ignores them when emitting verilogs.
For example, in XiangShan code base, rob.io.wb may contain EXU bundle with zero width pdest port. If tracing wb bundle blindly, ChiselDB will emit a `[-1:0]` port definition and raise missing pin warning on instanciation and the emu build will fail.

fix(ChiselDB): ignore zero width ports

---

src/main/scala/utility/ChiselTaggedTrace.scala
src/main/scala/utility/package.scala

1.Export the commit trace to XSPdb
2.More standardized naming, PerfCCT -> TaggedTrace
Still keep the perfcct alias

feat(ChiselTaggedTrace): XSPdb suport & rename PerfCCT to TaggedTrace
